-- MySQL Script generated by MySQL Workbench
-- Sat May 15 20:15:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ponchitodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ponchitodb` ;

CREATE SCHEMA IF NOT EXISTS `ponchitodb` DEFAULT CHARACTER SET latin1 COLLATE latin1_spanish_ci ;
USE `ponchitodb` ;

DROP TABLE IF EXISTS `ponchitodb`.`Ciudades` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Ciudades` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NULL,
  `pais` VARCHAR(20) NULL,
  PRIMARY KEY (`id_ciudad`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`LugaresAVisitar` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`LugaresAVisitar` (
  `id_lugar_a_visitar` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`id_lugar_a_visitar`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`FechasCircuitos` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`FechasCircuitos` (
  `id_fecha_circuito` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `fecha_salida` DATE NULL,
  `cant_personas` INT NULL,
  PRIMARY KEY (`id_fecha_circuito`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Hoteles` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Hoteles` (
  `id_hotel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `num_cuarto` INT NULL,
  `precio_cuarto` VARCHAR(45) NULL,
  `precio_desayuno` FLOAT NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Etapas` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Etapas` (
  `id_etapa` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `orden` INT NULL,
  `nombre_lugar` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `duracion` INT NULL,
  PRIMARY KEY (`id_etapa`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Circuitos` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Circuitos` (
  `id_circuito` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(5) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `ciudad_salida` VARCHAR(45) NULL,
  `pais_salida` VARCHAR(45) NULL,
  `ciudad_llegada` VARCHAR(45) NULL,
  `pais_llegada` VARCHAR(45) NULL,
  `duracion` INT NULL,
  `precio` FLOAT NOT NULL,
  `fecha_circuito_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `etapa_id` INT NOT NULL,
  `lugaravisitar_id` INT NOT NULL,
  PRIMARY KEY (`id_circuito`, `fecha_circuito_id`, `hotel_id`, `etapa_id`, `lugaravisitar_id`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE,
  INDEX `fk_Circuitos_FechasCircuitos1_idx` (`fecha_circuito_id` ASC) VISIBLE,
  INDEX `fk_Circuitos_Hoteles1_idx` (`hotel_id` ASC) VISIBLE,
  INDEX `fk_Circuitos_Etapas1_idx` (`etapa_id` ASC) VISIBLE,
  INDEX `fk_Circuitos_LugaresAVisitar1_idx` (`lugaravisitar_id` ASC) VISIBLE,
  CONSTRAINT `fk_Circuitos_FechasCircuitos1`
    FOREIGN KEY (`fecha_circuito_id`)
    REFERENCES `ponchitodb`.`FechasCircuitos` (`id_fecha_circuito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Circuitos_Hoteles1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `ponchitodb`.`Hoteles` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Circuitos_Etapas1`
    FOREIGN KEY (`etapa_id`)
    REFERENCES `ponchitodb`.`Etapas` (`id_etapa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Circuitos_LugaresAVisitar1`
    FOREIGN KEY (`lugaravisitar_id`)
    REFERENCES `ponchitodb`.`LugaresAVisitar` (`id_lugar_a_visitar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Simulaciones` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Simulaciones` (
  `id_simulacion` INT NOT NULL AUTO_INCREMENT,
  `codigo_simulacion` VARCHAR(45) NULL,
  `nombre_persona` VARCHAR(45) NULL,
  `fecha_salida` DATE NULL,
  `fecha_llegada` DATE NULL,
  `costo` FLOAT NULL,
  `ciudad_id` INT NOT NULL,
  `circuito_id` INT NOT NULL,
  PRIMARY KEY (`id_simulacion`, `ciudad_id`, `circuito_id`),
  INDEX `fk_Simulaciones_Ciudades1_idx` (`ciudad_id` ASC) VISIBLE,
  INDEX `fk_Simulaciones_Circuitos1_idx` (`circuito_id` ASC) VISIBLE,
  CONSTRAINT `fk_Simulaciones_Ciudades1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `ponchitodb`.`Ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Simulaciones_Circuitos1`
    FOREIGN KEY (`circuito_id`)
    REFERENCES `ponchitodb`.`Circuitos` (`id_circuito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Empleados` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`user` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS `ponchitodb`.`Reservaciones` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Reservaciones` (
  `id_reservacion` INT NOT NULL AUTO_INCREMENT,
  `codigo_reservacion` VARCHAR(45) NOT NULL,
  `nombre_cliente` VARCHAR(45) NULL,
  `direccion_cliente` VARCHAR(45) NULL,
  `tipo_pago` VARCHAR(45) NULL,
  `ciudad_id` INT NOT NULL,
  `circuito_id` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `ciudad_id`, `circuito_id`),
  INDEX `fk_Reservaciones_Ciudades1_idx` (`ciudad_id` ASC) VISIBLE,
  INDEX `fk_Reservaciones_Circuitos1_idx` (`circuito_id` ASC) VISIBLE,
  UNIQUE INDEX `codigo_reservacion_UNIQUE` (`codigo_reservacion` ASC) VISIBLE,
  CONSTRAINT `fk_Reservaciones_Ciudades1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `ponchitodb`.`Ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservaciones_Circuitos1`
    FOREIGN KEY (`circuito_id`)
    REFERENCES `ponchitodb`.`Circuitos` (`id_circuito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

DROP TABLE IF EXISTS `ponchitodb`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `ponchitodb`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(16) NOT NULL,
  `correo_electronico` VARCHAR(255) NULL,
  `contraseña` VARCHAR(32) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `Reservaciones_id_reservacion` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `Reservaciones_id_reservacion`),
  INDEX `fk_Clientes_Reservaciones1_idx` (`Reservaciones_id_reservacion` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Reservaciones1`
    FOREIGN KEY (`Reservaciones_id_reservacion`)
    REFERENCES `ponchitodb`.`Reservaciones` (`id_reservacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
